# Generated by Django 3.1.5 on 2021-01-20 02:58

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ALPRSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="FaceDetectionSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MotionDetectionSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("sensitivity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ObjectDetectionSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("threshold", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SoundDetectionSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("sensitivity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MotionDetectionRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFFFF", max_length=18),
                ),
                ("points", models.JSONField()),
                (
                    "motion_detection_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="detection.motiondetectionsettings",
                    ),
                ),
            ],
        ),
    ]
