# Generated by Django 3.1.5 on 2021-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_restructure_camera_detection_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='alprsettings',
            name='visualize',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facedetectionsettings',
            name='visualize',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motiondetectionsettings',
            name='visualize',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectdetectionsettings',
            name='visualize',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sounddetectionsettings',
            name='visualize',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
