# Generated by Django 4.2.6 on 2023-10-18 04:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0005_add_detection_visualize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motiondetectionregion",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
