# Generated by Django 3.1.5 on 2021-01-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
