.caches:
  - &cache_envs
    key: envs-$CI_COMMIT_REF_SLUG
    fallback_keys:
      - envs-$CI_DEFAULT_BRANCH
      - envs-default
    paths:
      - deploy/envs/

  - &cache_envs_pull
    <<: *cache_envs
    policy: pull

  - &cache_node_modules
    key: node_modules-$CI_COMMIT_REF_SLUG
    fallback_keys:
      - node_modules-$CI_DEFAULT_BRANCH
      - node_modules-default
    paths:
      - ui/node_modules/

  - &cache_node_modules_pull
    <<: *cache_node_modules
    policy: pull

image: busybox:glibc

setup:envs:
  cache:
    - *cache_envs
  script:
    - deploy/scripts/setup_envs.sh

setup:node:
  cache:
    - *cache_envs_pull
    - *cache_node_modules
  needs: [setup:envs]
  script:
    - deploy/scripts/setup_node_modules.sh

setup:migrations:
  cache:
    - *cache_envs_pull
  needs: [setup:envs]
  script:
    - deploy/scripts/setup_migrations.sh

build:
  cache:
    - *cache_envs_pull
    - *cache_node_modules_pull
  needs: [setup:node]
  script:
    - deploy/scripts/build.sh

lint:biome:
  cache:
    - *cache_envs_pull
    - *cache_node_modules_pull
  needs: [setup:node]
  script:
    - deploy/scripts/lint_biome.sh

lint:ruff:
  cache:
    - *cache_envs_pull
  needs: [setup:envs]
  script:
    - deploy/scripts/lint_ruff.sh
