# Generated by Django 3.1.5 on 2021-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_lowercase_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_ping',
            field=models.DateTimeField(null=True),
        ),
    ]
