# Generated by Django 3.1.5 on 2021-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_camera_last_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='force_tcp',
            field=models.BooleanField(default=True),
        ),
    ]
