# Generated by Django 3.1.5 on 2021-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0010_stream_force_tcp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="last_ping",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
