# Generated by Django 4.2.6 on 2024-09-23 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0011_last_ping_blank"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="last_ping",
            new_name="stream_start",
        ),
    ]
