# Generated by Django 3.1.5 on 2021-01-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulepart",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
