# Generated by Django 3.1.5 on 2021-01-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overlay", "0002_add_foreground_background_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overlay",
            name="x_pos",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="overlay",
            name="y_pos",
            field=models.SmallIntegerField(),
        ),
    ]
