# Generated by Django 4.2.6 on 2023-10-18 04:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overlay", "0003_allow_negative_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overlay",
            name="background",
            field=colorfield.fields.ColorField(
                default="#000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="overlay",
            name="foreground",
            field=colorfield.fields.ColorField(
                default="#FFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
